"""Export corrected/PAPER.md to DOCX (pandoc) and PDF (LibreOffice). Replaces the Mermaid block with a rendered figure."""
import re, subprocess, pypandoc, os
os.chdir('corrected'); t = open('PAPER.md').read()
t = re.sub(r'```mermaid.*?```', '![Study pipeline](figures/fig_pipeline.png)', t, flags=re.S)
t = t.replace('_Generated by', '')
open('PAPER_export.md', 'w').write(t)
pypandoc.convert_file('PAPER_export.md', 'docx', outputfile='PAPER.docx', extra_args=['--from=markdown+pipe_tables+tex_math_dollars+raw_tex-yaml_metadata_block', '--resource-path=.', '--toc', '--toc-depth=2', '--number-sections=false'])
css = open('../manuscript.css').read(); open('_style.css', 'w').write(css)
pypandoc.convert_file('PAPER_export.md', 'html5', outputfile='PAPER.html', extra_args=['--from=markdown+pipe_tables+tex_math_dollars+raw_tex-yaml_metadata_block', '--standalone', '--embed-resources', '--mathml', '--css=_style.css', '--toc', '--toc-depth=2', '--metadata=title:Learning River Response Across Nepal\'s Himalayan Basins', '--resource-path=.'])
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    br = p.chromium.launch(executable_path='/opt/pw-browsers/chromium' if os.path.exists('/opt/pw-browsers/chromium') else None); pg = br.new_page(); pg.goto('file://' + os.path.abspath('PAPER.html')); pg.wait_for_timeout(1500)
    pg.pdf(path='PAPER.pdf', format='A4', margin={'top': '18mm', 'bottom': '18mm', 'left': '16mm', 'right': '16mm'}, print_background=True, display_header_footer=True, footer_template='<div style="font-size:8px;width:100%;text-align:center"><span class="pageNumber"></span> / <span class="totalPages"></span></div>', header_template='<div></div>'); br.close()
os.remove('_style.css')
os.remove('PAPER_export.md'); print({f: os.path.getsize(f) // 1024 for f in ('PAPER.docx', 'PAPER.html', 'PAPER.pdf')})
